const VALID_TRANSITIONS = {
  OPEN: ["IN_REVIEW", "CLOSED"],
  IN_REVIEW: ["WAITING", "RESOLVED", "CLOSED"],
  WAITING: ["IN_REVIEW", "RESOLVED"],
  RESOLVED: ["CLOSED", "IN_REVIEW"],
  CLOSED: ["OPEN"],
};
export default VALID_TRANSITIONS;
